name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-secret-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{ inputs.AWS_REGION }}
      - run: npm i
      - run: npm run build
      - run: aws s3 sync ./build s3://${{ secrets.s3_BUCKET_NAME }}